# Generated by Django 5.1.7 on 2025-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdfanalysis",
            old_name="upload_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pdfanalysis",
            name="is_phishing",
            field=models.BooleanField(),
        ),
    ]
